ALTER TABLE devices ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS region VARCHAR(100);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS wifi_ssid VARCHAR(255);
